services:
  react-app:
    image: node:20-alpine
    container_name: react_rick_morty
    working_dir: /app
    volumes:
      - ./app/:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - CHOKIDAR_USEPOLLING=true